version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
  app:
    build: .
    profiles:
      - prod
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PORT=${PORT}
      - ROOT=${ROOT}
      - MIGRATE=${MIGRATE}
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
